// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6owjdlmx5YEk-EUjqI3m6qBDpE6Ede8k',
    appId: '1:862053198618:android:b070c389a083f55c771aa3',
    messagingSenderId: '862053198618',
    projectId: 'taletale-f5808',
    storageBucket: 'taletale-f5808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlTaJTRtvhf0M-Jl8VTNl0ZjnnFvrji6U',
    appId: '1:862053198618:ios:be61a2e63c6b7b11771aa3',
    messagingSenderId: '862053198618',
    projectId: 'taletale-f5808',
    storageBucket: 'taletale-f5808.appspot.com',
    iosClientId: '862053198618-vuasbsjjfp00rfm1hqscu94fg82h45v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlTaJTRtvhf0M-Jl8VTNl0ZjnnFvrji6U',
    appId: '1:862053198618:ios:be61a2e63c6b7b11771aa3',
    messagingSenderId: '862053198618',
    projectId: 'taletale-f5808',
    storageBucket: 'taletale-f5808.appspot.com',
    iosClientId: '862053198618-vuasbsjjfp00rfm1hqscu94fg82h45v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
