// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTnfVaT4irrLaL1hqXjoJhd3Zyc7OFqo',
    appId: '1:590736670484:web:98287631c6b1ff76020c01',
    messagingSenderId: '590736670484',
    projectId: 'taletale-a9e9a',
    authDomain: 'taletale-a9e9a.firebaseapp.com',
    storageBucket: 'taletale-a9e9a.appspot.com',
    measurementId: 'G-S1VEE5QX40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLwO7l-3DJCbEIGe39l9uEPrFDoAfhmE',
    appId: '1:590736670484:android:e081a4275118536b020c01',
    messagingSenderId: '590736670484',
    projectId: 'taletale-a9e9a',
    storageBucket: 'taletale-a9e9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRuWC4DeVgCGQuux4R7b2vqmtrzmQaFm0',
    appId: '1:590736670484:ios:6e6d6e68b87bd9a4020c01',
    messagingSenderId: '590736670484',
    projectId: 'taletale-a9e9a',
    storageBucket: 'taletale-a9e9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRuWC4DeVgCGQuux4R7b2vqmtrzmQaFm0',
    appId: '1:590736670484:ios:6e6d6e68b87bd9a4020c01',
    messagingSenderId: '590736670484',
    projectId: 'taletale-a9e9a',
    storageBucket: 'taletale-a9e9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
